[tool]
[tool.poetry]
name = "reddit_python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
Flask = "1.0.3"
PyYAML = "5.1.1"
praw = "6.2.0"
prawcore = "1.0.1"
